apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coreapi
  template:
    metadata:
      labels:
        app: coreapi
    spec:
      containers:
        - name: coreapi-container
          image: adityacodes30/ondc-api
          env:
            - name: RABBIT_Q1_URL
              value: "amqp://q1service:8080"
          ports:
            - containerPort: 5001
