apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue2
  template:
    metadata:
      labels:
        app: queue2
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.17-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
