apiVersion: v1
kind: Service
metadata:
  name: q2service
spec:
  selector:
    app: queue2
  ports:
    - name: queue
      port: 9090
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 9091
      targetPort: 15672
      protocol: TCP
  type: ClusterIP
