# -*- coding: utf-8 -*-
"""similarity_scoring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZEoSXfB61D8Nzco9J3_oWkMCQxcS15r
"""

import spacy

nlp= spacy.load("en_core_web_sm")

nlp

g1=nlp("how")

g2=nlp("hoe")

g2.similarity(g1)

import spacy

def calculate_similarity(text1, text2, model="en_core_web_sm"):
    # Load the spaCy model
    nlp = spacy.load(model)

    # Process the texts
    doc1 = nlp(text1)
    doc2 = nlp(text2)

    # Calculate the similarity
    similarity_score = doc1.similarity(doc2)

    return similarity_score

# Example usage:
text1 = "how"
text2 = "hoe"
similarity = calculate_similarity(text1, text2)
#print("Similarity between '{}' and '{}': {}".format(text1, text2, similarity))

