apiVersion: v1
kind: Service
metadata:
  name: q1service
spec:
  selector:
    app: queue1
  ports:
    - name: queue
      port: 8080
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 8081
      targetPort: 15672
      protocol: TCP
  type: ClusterIP

